AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - config/initializers/**/*

Documentation:
  Enabled: false

IfUnlessModifier:
  Enabled: false

# Causes issues with Rails' #update method
RedundantMerge:
  Enabled: false

# Behavior is changing in Ruby 3, let's just leave this alone for now
MutableConstant:
  Enabled: false

StructInheritance:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

MultilineMethodCallIndentation:
  Enabled: false

MultilineOperationIndentation:
  Enabled: false

GuardClause:
  Enabled: false

# Causes issues with things like port numbers
NumericLiterals:
  Enabled: false

# We'll use CodeClimate or another tool to track this...
MethodLength:
  Enabled: false

PerceivedComplexity:
  Enabled: false

AbcSize:
  Enabled: false

ClassLength:
  Enabled: false

# https://github.com/bbatsov/ruby-style-guide/issues/270 kinda sums it up
Lambda:
  Enabled: false

DotPosition:
  EnforcedStyle: trailing
